  my:
    custom:
      property: Hello from application properties
      login-url: test-login
      credentials:
        user: test-user
        password: pass
  spring:
    application:
      name: kamlit